version: "3.0"
services:
  rpi:
    image: lukechilds/dockerpi:vm
    # command: pi3
    volumes:
      - ./sdcard:/sdcard
      - ./images/prepared/filesystem.img:/sdcard/filesystem.img
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
    ports:
      - 5022:5022
    restart: always
