---
- name: Debug passphrase variables
  debug:
    var: wifi_settings.wifi_networks

- name: Configure Networkmanager
  ansible.builtin.template:
    src: templates/NetworkManager.conf.j2
    dest: /etc/NetworkManager/NetworkManager.conf
    owner: root
    group: root
    mode: '0744'

- name: Copy Networkmanager dispatcher script
  ansible.builtin.template:
    src: templates/00-virtualuap0.j2
    dest: /etc/NetworkManager/dispatcher.d/00-virtualwlan1
    owner: root
    group: root
    mode: '0744'

- name: Configure WiFi network
  nmcli:
    conn_name: "{{ item.name }}"
    state: present
    type: wifi
    ssid: "{{ item.ssid }}"
    ifname: "{{ item.interface }}"
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ item.psk }}"
  with_items: "{{ wifi_settings.wifi_networks }}"

- name: Set priority for elimu-connect connection
  ansible.builtin.shell:
    cmd: nmcli connection modify "elimu-connect" connection.autoconnect-priority 110

- name: Configure dhcpcd
  ansible.builtin.template:
    src: templates/dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Disable IPv6 with sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: "present"
    reload: "yes"
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

